export const FETCH_MAIN_EPISODE_LOADING = 'FETCH_MAIN_EPISODE_LOADING';
export const FETCH_MAIN_EPISODE_SUCCESS = 'FETCH_MAIN_EPISODE_SUCCESS';
export const FETCH_MAIN_EPISODE_FAIL = 'FETCH_MAIN_EPISODE_FAIL';

export const FETCH_DETAIL_EPISODE_LOADING = 'FETCH_DETAIL_EPISODE_LOADING';
export const FETCH_DETAIL_EPISODE_SUCCESS = 'FETCH_DETAIL_EPISODE_SUCCESS';
export const FETCH_DETAIL_EPISODE_FAIL = 'FETCH_DETAIL_EPISODE_FAIL';
