export const FETCH_ALL_EPISODE_LOADING = 'FETCH_ALL_EPISODE_LOADING';
export const FETCH_ALL_EPISODE_SUCCESS = 'FETCH_ALL_EPISODE_SUCCESS';
export const FETCH_ALL_EPISODE_FAIL = 'FETCH_ALL_EPISODE_FAIL';

export const FETCH_DETAIL_EPISODE_LOADING = 'FETCH_DETAIL_EPISODE_LOADING';
export const FETCH_DETAIL_EPISODE_SUCCESS = 'FETCH_DETAIL_EPISODE_SUCCESS';
export const FETCH_DETAIL_EPISODE_FAIL = 'FETCH_DETAIL_EPISODE_FAIL';
