export const FETCH_MAIN_CHARACTER_SUCCESS = 'FETCH_MAIN_CHARACTER_SUCCESS';
export const FETCH_MAIN_CHARACTER_FAIL = 'FETCH_MAIN_CHARACTER_FAIL';

export const FETCH_DETAIL_CHARACTER_LOADING = 'FETCH_DETAIL_CHARACTER_LOADING';
export const FETCH_DETAIL_CHARACTER_SUCCESS = 'FETCH_DETAIL_CHARACTER_SUCCESS';
export const FETCH_DETAIL_CHARACTER_FAIL = 'FETCH_DETAIL_CHARACTER_FAIL';
